"""
The training run, start to finish, on rented cloud GPUs.

Trains a 777M-parameter (161M active per token) DeepSeek-style Mixture-of-
Experts chat model from scratch on ~6B tokens, split into two pretraining
phases on separate machines and a third stage that fine-tunes.

    PHASE 1
        python verify_cloud_run.py                   # free: validate the whole plan
        modal run cloud_run.py --stage budget         # free: print the cost ceiling
        modal run cloud_run.py --stage preflight      # ~$0.35: measure real speed first
        modal run --detach cloud_run.py --stage phase1
        # then move three files across (the run prints the exact commands)

    PHASE 2
        modal run --detach cloud_run.py --stage phase2
        modal volume get llm-v2 checkpoints/chat_final.pt ../checkpoints/chat_final.pt

Why two phases. Phase 1 pretrains the first ~52% of the schedule; phase 2
continues it and then chat-tunes. The learning rate follows ONE cosine
curve across both phases (train.py's --schedule-start / --schedule-end), so
the model anneals properly at the very end instead of decaying to zero
halfway through and being re-warmed from scratch.

What crosses the boundary: the tokenizer (~6MB), the validation tokens
(~20MB) and the phase-1 weights in bfloat16 (~1.5GB). Optimizer state is NOT
carried across -- that would be a ~9GB transfer for a small quality gain --
so phase 2 starts a fresh AdamW and re-warms over 150 steps onto the same
curve.

Spending safety, in three layers:
  * Every function has a hard timeout. worst_case_by_phase() below multiplies
    those timeouts by the provider's published prices, and an assert at import
    time refuses to load this module if any phase could exceed its budget in
    PHASE_BUDGET_USD. A bad plan fails locally, before anything runs.
  * Every command line is built by a plain function (pretrain_arguments and
    friends) so verify_cloud_run.py can check each flag against the target
    script's parser. A typo in a flag is caught for free rather than on a
    rented H100.
  * Every stage writes a marker file on the volume, so re-running after a
    failure skips work that was already paid for.
"""
import json
import os
import subprocess
import sys
import threading
import time

import modal

HERE = os.path.dirname(os.path.abspath(__file__))

# ----------------------------------------------------------------------
# The plan
# ----------------------------------------------------------------------

MODEL_SIZE = "chat"          # the preset in config.py: 777M total / 161M active, 32 routed experts
BLOCK_SIZE = 1024            # must equal that preset's max_sequence_length
VOCAB_SIZE = 32768           # a 65k vocabulary would spend ~18% of every step in the output layer alone

# FineWeb-Edu ships as 14 parquet shards of ~2.15GB, each roughly 0.8B tokens at this vocabulary
# size. Phase 2 reads DIFFERENT shards, so no text is ever seen twice.
FINEWEB_REPO = "HuggingFaceFW/fineweb-edu"
# Measured on the preflight: 179k tokens/s, so phase 2 will consume ~2.65B tokens in its
# 252 minutes. Three shards (~2.25B) would mean repeating data, so phase 2 reads four.
FINEWEB_SHARDS = {1: (0, 1, 2), 2: (3, 4, 5, 6, 7)}
TOKENIZER_SAMPLE_BYTES = 1_500_000_000   # text used to train the byte-level BPE tokenizer

CHAT_DATASET = "HuggingFaceTB/smol-smoltalk"          # built specifically for 135M-360M models
CHAT_EXTRA_DATASET = ("HuggingFaceTB/smoltalk", "everyday-conversations")
# Measured after the first chat tune: at x3 the everyday-conversations subset was only ~1.5%
# of packed rows, and the model answered a bare "hi" with a lecture on quantum mechanics.
# x25 brings small talk to roughly 12% of rows.
CHAT_EXTRA_REPEATS = 25

# Conversations generated by persona_data.py: who built the model, what it is, what it
# cannot do, and the pattern that answers "what is my name?" with "YOUR name is ...".
# None of this exists in any public dataset, and none of it can be learned from more
# pretraining, so it has to be written and mixed in here.
# 140k sessions pack into ~12.7k rows: 3.3% of the chat set, seen about 2.7 times over
# the run. The first attempt used 20k single exchanges, which packed to 0.18% -- far too
# little to teach anything, and raising it by repetition would have taught parroting.
PERSONA_CONVERSATIONS = 140_000

PRETRAIN_MINUTES = {1: 276, 2: 340}
PRETRAIN_TIMEOUT_MINUTES = {1: 300, 2: 358}
# PINNED, not derived from the minutes above. Phase 1 already ran with schedule-end
# 0.5227, so this is where its learning rate actually stopped. Recomputing the split
# after lengthening phase 2 would start phase 2 lower on the curve than phase 1 ended,
# i.e. the learning rate would jump back UP mid-training.
SCHEDULE_SPLIT = 0.5227272727272727

# The third stage exists only to fine-tune. One long run beats two short ones: the
# cosine schedule completes once instead of restarting, and the ~$0.35 of container
# startup is paid once. 85 minutes is ~1.9 passes over the packed chat data.
FINETUNE_MINUTES = 80
FINETUNE_TIMEOUT_MINUTES = 88

MICRO_BATCH_SIZE = 24        # sequences resident at once: ~24k tokens per micro-batch
GRAD_ACCUM = 12              # -> 294,912 tokens per optimizer step
MAX_LEARNING_RATE = 6e-4
MIN_LEARNING_RATE = 6e-5
WARMUP_STEPS = {1: 300, 2: 150}   # phase 2 only needs a short re-warm for its fresh optimizer

FINETUNE_MICRO_BATCH = 24
FINETUNE_GRAD_ACCUM = 3
FINETUNE_MAX_LR = 2e-4
FINETUNE_MIN_LR = 2e-5

# ----------------------------------------------------------------------
# Budget
# ----------------------------------------------------------------------

# What each phase is allowed to spend. Phases 1 and 2 are finished and came in under
# budget; phase 3 is the fine-tune, and its figure is what was left after roughly $0.70
# went on a first launch that was stopped early once the persona mix was found to be too
# small. Every timeout below is sized against these, and the assert underneath refuses to
# import the module if a plan could exceed one.
PHASE_BUDGET_USD = {1: 30.0, 2: 30.0, 3: 7.80}
PRICE_PER_SECOND = {"H100": 0.001097, "cpu_core": 0.0000131, "memory_gib": 0.00000222}

CPU_STAGE = dict(cpu=16, memory_gib=32, gpu=None)
GPU_STAGE = dict(cpu=4, memory_gib=32, gpu="H100")
TINY_STAGE = dict(cpu=0.125, memory_gib=1, gpu=None)

PREPARE_TIMEOUT_MINUTES = 60
# Chat-only preparation skips the FineWeb download and tokenizer training, so it needs
# far less wall clock -- and on the fine-tune phase every minute of timeout is budget.
CHAT_PREPARE_TIMEOUT_MINUTES = 25
PREFLIGHT_TIMEOUT_MINUTES = 10
EXPORT_TIMEOUT_MINUTES = 15
# must exceed the WHOLE phase-2 chain: data prep + pretrain + chat tuning + export,
# or the orchestrator is killed before it can launch the later stages
ORCHESTRATOR_TIMEOUT_MINUTES = 500


def stage_cost_per_second(stage):
    gpu_price = PRICE_PER_SECOND[stage["gpu"]] if stage["gpu"] else 0.0
    return (gpu_price + stage["cpu"] * PRICE_PER_SECOND["cpu_core"]
            + stage["memory_gib"] * PRICE_PER_SECOND["memory_gib"])


def worst_case_by_phase():
    """The most each phase can possibly be charged: every stage running to
    its full Modal timeout."""
    prepare = stage_cost_per_second(CPU_STAGE) * PREPARE_TIMEOUT_MINUTES * 60
    chat_prepare = stage_cost_per_second(CPU_STAGE) * CHAT_PREPARE_TIMEOUT_MINUTES * 60
    preflight_cost = stage_cost_per_second(GPU_STAGE) * PREFLIGHT_TIMEOUT_MINUTES * 60
    export_cost = stage_cost_per_second(CPU_STAGE) * EXPORT_TIMEOUT_MINUTES * 60
    orchestrator = stage_cost_per_second(TINY_STAGE) * ORCHESTRATOR_TIMEOUT_MINUTES * 60
    pretrain = {phase: stage_cost_per_second(GPU_STAGE) * PRETRAIN_TIMEOUT_MINUTES[phase] * 60 for phase in (1, 2)}
    finetune_cost = stage_cost_per_second(GPU_STAGE) * FINETUNE_TIMEOUT_MINUTES * 60
    return {
        1: {"data prep": prepare, "preflight": preflight_cost, "pretrain phase 1": pretrain[1],
            "orchestrator": orchestrator},
        2: {"data prep": prepare, "pretrain phase 2": pretrain[2],
            "export": export_cost, "orchestrator": orchestrator},
        3: {"chat data prep": chat_prepare, "chat tuning": finetune_cost,
            "export": export_cost, "orchestrator": orchestrator},
    }


def print_budget():
    print("\nWORST CASE per phase (every stage hitting its full timeout)")
    for phase, stages in worst_case_by_phase().items():
        print(f"  phase {phase} (budget ${PHASE_BUDGET_USD[phase]:.2f}):")
        for name, cost in stages.items():
            print(f"    {name:<20s} ${cost:6.2f}")
        print(f"    {'TOTAL':<20s} ${sum(stages.values()):6.2f}")
    expected = {
        1: 0.45 + 0.30 + stage_cost_per_second(GPU_STAGE) * (PRETRAIN_MINUTES[1] + 8) * 60 + 0.03,
        2: 0.40 + stage_cost_per_second(GPU_STAGE) * (PRETRAIN_MINUTES[2] + 8) * 60 + 0.10,
        3: 0.20 + stage_cost_per_second(GPU_STAGE) * (FINETUNE_MINUTES + 6) * 60 + 0.10,
    }
    print("\n  EXPECTED: " + ", ".join(f"phase {phase} ~${cost:.2f}"
                                       for phase, cost in expected.items())
          + f", total ~${sum(expected.values()):.2f}")


for _phase, _stages in worst_case_by_phase().items():
    assert sum(_stages.values()) <= PHASE_BUDGET_USD[_phase], (
        f"phase {_phase} could be charged ${sum(_stages.values()):.2f}, over its "
        f"${PHASE_BUDGET_USD[_phase]:.2f} budget -- lower a timeout before running anything")

# ----------------------------------------------------------------------
# Modal setup
# ----------------------------------------------------------------------

app = modal.App("llm-v2")

image = (
    modal.Image.debian_slim(python_version="3.11")
    .pip_install("torch==2.6.0", "numpy", "tokenizers", "datasets", "pyarrow",
                 "huggingface_hub", "hf_transfer")
    .env({"HF_HUB_ENABLE_HF_TRANSFER": "1", "KMP_DUPLICATE_LIB_OK": "TRUE", "PYTHONUNBUFFERED": "1"})
    .add_local_dir(HERE, remote_path="/root/training",
                   ignore=["__pycache__", "*.pyc", "db", "static", "*.jsonl", "*.txt", "*.md"])
)

VOLUME = modal.Volume.from_name("llm-v2", create_if_missing=True)
MOUNTS = {"/vol": VOLUME}

DATA_DIR = "/vol/data"
TOKENIZER_DIR = "/vol/tokenizer"
CHECKPOINT_DIR = "/vol/checkpoints"
MARKER_DIR = "/vol/markers"
TRAINING_DIR = "/root/training"

# ----------------------------------------------------------------------
# Command lines, as data so they can be validated without running anything
# ----------------------------------------------------------------------

def pretrain_arguments(phase, data_dir=DATA_DIR, tokenizer_dir=TOKENIZER_DIR, checkpoint_dir=CHECKPOINT_DIR,
                       resume_from="", minutes=None, schedule_start=None, warmup_steps=None):
    """The exact train.py command line for one pretraining phase.

    The override parameters exist for restarting an interrupted phase. A run
    that stopped a third of the way through must not restart the learning-rate
    curve from the beginning: pass the minutes that remain and the point on the
    curve it had already reached, and the schedule carries on from there."""
    arguments = [
        "--size", MODEL_SIZE, "--tag", f"base{phase}", "--data-dir", data_dir,
        "--tokenizer-dir", tokenizer_dir, "--ckpt-dir", checkpoint_dir,
        "--minutes", PRETRAIN_MINUTES[phase] if minutes is None else minutes,
        "--lr-schedule", "time",
        "--schedule-start", (0.0 if phase == 1 else SCHEDULE_SPLIT) if schedule_start is None else schedule_start,
        "--schedule-end", SCHEDULE_SPLIT if phase == 1 else 1.0,
        "--micro-batch-size", MICRO_BATCH_SIZE, "--grad-accum", GRAD_ACCUM,
        "--max-lr", MAX_LEARNING_RATE, "--min-lr", MIN_LEARNING_RATE,
        "--warmup-steps", WARMUP_STEPS[phase] if warmup_steps is None else warmup_steps,
        "--eval-interval", 500, "--eval-iters", 20, "--checkpoint-interval", 1000,
    ]
    if resume_from:
        # continues the SAME run: optimizer moments, step counter and best-so-far restored
        arguments += ["--resume", resume_from]
    elif phase == 2:
        # weights only: phase 1's optimizer state stays behind on the other machine
        arguments += ["--init-from", f"{checkpoint_dir}/phase1_weights.pt"]
    return arguments


def preflight_arguments(data_dir=DATA_DIR, tokenizer_dir=TOKENIZER_DIR):
    """A three-minute version of the real thing: same model, same data, same
    batch shape, nothing saved."""
    return [
        "--size", MODEL_SIZE, "--tag", "preflight", "--data-dir", data_dir,
        "--tokenizer-dir", tokenizer_dir, "--ckpt-dir", "/tmp/preflight",
        "--minutes", 3.0, "--lr-schedule", "time",
        "--micro-batch-size", MICRO_BATCH_SIZE, "--grad-accum", GRAD_ACCUM,
        "--max-lr", MAX_LEARNING_RATE, "--min-lr", MIN_LEARNING_RATE, "--warmup-steps", 50,
        "--eval-interval", 10 ** 9, "--checkpoint-interval", 10 ** 9, "--log-interval", 5,
    ]


def finetune_arguments(base_checkpoint, data_dir=DATA_DIR, checkpoint_dir=CHECKPOINT_DIR):
    return [
        "--init-from", base_checkpoint, "--data-dir", data_dir, "--ckpt-dir", checkpoint_dir,
        "--tag", "chat", "--minutes", FINETUNE_MINUTES, "--lr-schedule", "time", "--epochs", 3.0,
        "--batch-size", FINETUNE_MICRO_BATCH, "--grad-accum", FINETUNE_GRAD_ACCUM,
        "--max-lr", FINETUNE_MAX_LR, "--min-lr", FINETUNE_MIN_LR, "--warmup-steps", 100,
        "--eval-interval", 200, "--eval-iters", 10, "--checkpoint-interval", 400,
    ]


# ----------------------------------------------------------------------
# Small helpers used inside the containers
# ----------------------------------------------------------------------

def marker_path(name):
    return os.path.join(MARKER_DIR, f"{name}.json")


def is_done(name):
    return os.path.exists(marker_path(name))


def mark_done(name, **details):
    os.makedirs(MARKER_DIR, exist_ok=True)
    with open(marker_path(name), "w", encoding="utf-8") as handle:
        json.dump({"finished_at": time.strftime("%Y-%m-%d %H:%M:%S"), **details}, handle, indent=2)
    VOLUME.commit()


def commit_periodically(interval_seconds=300):
    """Commits the volume on a timer; returns a function that stops it.

    Checkpoints written mid-run only become durable once the volume is
    committed. Without this, a run that times out or crashes at hour four
    leaves the volume exactly as it was at hour zero."""
    stop_event = threading.Event()

    def loop():
        while not stop_event.wait(interval_seconds):
            try:
                VOLUME.commit()
                print(f"[modal] volume committed at {time.strftime('%H:%M:%S')}", flush=True)
            except Exception as error:
                print(f"[modal] commit failed: {error}", flush=True)

    threading.Thread(target=loop, daemon=True).start()
    return stop_event.set


def run_script(script_name, arguments):
    command = [sys.executable, f"{TRAINING_DIR}/{script_name}"] + [str(argument) for argument in arguments]
    print("[modal] " + " ".join(command), flush=True)
    completed = subprocess.run(command, cwd=TRAINING_DIR)
    if completed.returncode != 0:
        raise RuntimeError(f"{script_name} exited with code {completed.returncode}")


def require(*paths):
    missing = [path for path in paths if not os.path.exists(path)]
    if missing:
        raise SystemExit("missing required file(s) on the volume:\n  " + "\n  ".join(missing))


# ----------------------------------------------------------------------
# Stage 1: data
# ----------------------------------------------------------------------

@app.function(image=image, cpu=CPU_STAGE["cpu"], memory=CPU_STAGE["memory_gib"] * 1024,
              timeout=PREPARE_TIMEOUT_MINUTES * 60, volumes=MOUNTS, scaledown_window=2)
def prepare_data(phase: int):
    """Tokenizer (phase 1 only), pretraining tokens, and -- in phase 2 --
    the packed chat dataset."""
    sys.path.insert(0, TRAINING_DIR)
    for directory in (DATA_DIR, TOKENIZER_DIR, CHECKPOINT_DIR, MARKER_DIR):
        os.makedirs(directory, exist_ok=True)

    if phase == 1 and not is_done("tokenizer"):
        _train_tokenizer()
    require(f"{TOKENIZER_DIR}/tokenizer.json")   # in phase 2 this was uploaded from phase 1

    if not is_done(f"pretrain_data_phase{phase}"):
        _build_pretraining_tokens(phase)

    if phase == 2 and not is_done("chat_data"):
        _build_chat_data()

    VOLUME.commit()
    print("[modal] data ready:", sorted(os.listdir(DATA_DIR)), flush=True)


def _download_shard(shard_index):
    from huggingface_hub import hf_hub_download
    print(f"[modal] downloading FineWeb-Edu shard {shard_index}...", flush=True)
    return hf_hub_download(FINEWEB_REPO, f"sample/10BT/{shard_index:03d}_00000.parquet",
                           repo_type="dataset", local_dir="/tmp/fineweb")


def _train_tokenizer():
    """Byte-level BPE trained on our own text, exactly as tokenizer_train.py
    does, on a sample taken from the first shard."""
    import pyarrow.parquet as pq

    from download_pretrain_data import clean_text

    shard_path = _download_shard(FINEWEB_SHARDS[1][0])
    sample_path = "/tmp/tokenizer_sample.txt"
    written = 0
    with open(sample_path, "w", encoding="utf-8") as handle:
        for batch in pq.ParquetFile(shard_path).iter_batches(batch_size=10000, columns=["text"]):
            for text in batch.column(0).to_pylist():
                if not text or len(text) < 200:
                    continue
                cleaned = clean_text(text)
                handle.write(cleaned + "\n")
                written += len(cleaned)
            if written >= TOKENIZER_SAMPLE_BYTES:
                break
    print(f"[modal] training tokenizer on {written/1e9:.2f} GB of text...", flush=True)
    run_script("tokenizer_train.py", ["--input", sample_path, "--vocab-size", VOCAB_SIZE,
                                       "--out-dir", TOKENIZER_DIR])
    os.remove(sample_path)
    mark_done("tokenizer", vocab_size=VOCAB_SIZE, sample_bytes=written)


def _build_pretraining_tokens(phase):
    """Streams this phase's shards through the tokenizer into a flat uint16
    token file. Memory stays flat: one parquet row-batch at a time."""
    import itertools

    import numpy as np
    import pyarrow.parquet as pq
    from tokenizers import Tokenizer

    from download_pretrain_data import clean_text

    tokenizer = Tokenizer.from_file(f"{TOKENIZER_DIR}/tokenizer.json")
    end_of_text = tokenizer.token_to_id("<|endoftext|>")
    assert tokenizer.get_vocab_size() <= 65536, "vocabulary must fit in uint16"

    train_path = f"{DATA_DIR}/train.bin"
    temporary_path = train_path + ".tmp"
    validation_path = f"{DATA_DIR}/val.bin"
    # phase 1 carves out a validation set; phase 2 reuses that same file (carried across with
    # the tokenizer) so the loss curves from the two phases are directly comparable
    validation_target = 10_000_000 if phase == 1 else 0
    validation_written = 0
    total_tokens, documents, started = 0, 0, time.time()

    validation_output = open(validation_path + ".tmp", "wb") if validation_target else None
    with open(temporary_path, "wb") as output:
        for shard_index in FINEWEB_SHARDS[phase]:
            shard_path = _download_shard(shard_index)
            for batch in pq.ParquetFile(shard_path).iter_batches(batch_size=20000, columns=["text"]):
                texts = [clean_text(text) for text in batch.column(0).to_pylist() if text and len(text) >= 200]
                if not texts:
                    continue
                encodings = tokenizer.encode_batch(texts)
                token_count = sum(len(encoding.ids) + 1 for encoding in encodings)
                tokens = np.fromiter(
                    itertools.chain.from_iterable(encoding.ids + [end_of_text] for encoding in encodings),
                    dtype=np.uint16, count=token_count,
                )
                if validation_output is not None and validation_written < validation_target:
                    take = min(validation_target - validation_written, len(tokens))
                    validation_output.write(tokens[:take].tobytes())
                    validation_written += take
                    tokens = tokens[take:]
                output.write(tokens.tobytes())
                total_tokens += len(tokens)
                documents += len(texts)
                if documents % 200000 < 20000:
                    print(f"[modal] {documents:,} documents, {total_tokens/1e9:.2f}B tokens, "
                          f"{total_tokens/max(1.0, time.time()-started)/1e6:.1f}M tokens/s", flush=True)
            os.remove(shard_path)

    if validation_output is not None:
        validation_output.close()
        os.replace(validation_path + ".tmp", validation_path)
    os.replace(temporary_path, train_path)
    require(validation_path)

    print(f"[modal] phase {phase}: {total_tokens/1e9:.2f}B training tokens from {documents:,} documents "
          f"in {(time.time()-started)/60:.1f} min", flush=True)
    mark_done(f"pretrain_data_phase{phase}", tokens=total_tokens, documents=documents,
              shards=list(FINEWEB_SHARDS[phase]))


def _build_chat_data():
    """Packs real conversations into fixed-length rows (see sft_data.py)."""
    from datasets import load_dataset
    from tokenizers import Tokenizer

    import sft_data
    from chat_format import ChatSpecialTokens

    tokenizer_path = f"{TOKENIZER_DIR}/tokenizer.json"
    special_tokens = ChatSpecialTokens(Tokenizer.from_file(tokenizer_path))
    encode_kwargs = {"tokenizer_path": tokenizer_path, "block_size": BLOCK_SIZE}

    def encode(dataset):
        return dataset.select_columns(["messages"]).map(
            sft_data.encode_examples, batched=True, batch_size=500, num_proc=16,
            fn_kwargs=encode_kwargs, remove_columns=["messages"],
        )

    print(f"[modal] downloading {CHAT_DATASET}...", flush=True)
    train_parts = [encode(load_dataset(CHAT_DATASET, split="train").shuffle(seed=1337))]
    everyday = encode(load_dataset(*CHAT_EXTRA_DATASET, split="train"))
    train_parts += [everyday] * CHAT_EXTRA_REPEATS
    train_parts.append(encode(_persona_dataset()))

    validation = load_dataset(CHAT_DATASET, split="test")
    validation = encode(validation.select(range(min(3000, len(validation)))))

    for split_name, parts in (("train", train_parts), ("val", [validation])):
        ids, labels, stats = sft_data.pack_encoded(parts, BLOCK_SIZE, special_tokens.end_of_text)
        sft_data.save_split(DATA_DIR, split_name, ids, labels)
        print(f"[modal] chat {split_name}: {stats['rows']:,} rows, {stats['conversations']:,} conversations "
              f"({stats['conversations_per_row']:.1f} per row), "
              f"{stats['supervised_fraction']*100:.0f}% of positions supervised", flush=True)
    mark_done("chat_data")


def _persona_dataset():
    """The hand-written identity and memory conversations, as a Dataset."""
    from datasets import Dataset

    import persona_data

    rows = persona_data.generate(PERSONA_CONVERSATIONS)
    print(f"[modal] persona set: {len(rows):,} conversations about "
          f"{persona_data.MODEL_NAME} and {persona_data.CREATOR}", flush=True)
    return Dataset.from_list(rows)


@app.function(image=image, cpu=CPU_STAGE["cpu"], memory=CPU_STAGE["memory_gib"] * 1024,
              timeout=CHAT_PREPARE_TIMEOUT_MINUTES * 60, volumes=MOUNTS, scaledown_window=2)
def prepare_chat_data():
    """Packs the chat dataset only -- for a machine that already has the
    tokenizer and a pretrained checkpoint uploaded to its volume, and needs
    nothing from FineWeb."""
    sys.path.insert(0, TRAINING_DIR)
    for directory in (DATA_DIR, TOKENIZER_DIR, CHECKPOINT_DIR, MARKER_DIR):
        os.makedirs(directory, exist_ok=True)
    require(f"{TOKENIZER_DIR}/tokenizer.json")

    if not is_done("chat_data"):
        _build_chat_data()

    VOLUME.commit()
    print("[modal] chat data ready:", sorted(os.listdir(DATA_DIR)), flush=True)


# ----------------------------------------------------------------------
# Stage 2: preflight
# ----------------------------------------------------------------------

@app.function(image=image, gpu=GPU_STAGE["gpu"], cpu=GPU_STAGE["cpu"],
              memory=GPU_STAGE["memory_gib"] * 1024, timeout=PREFLIGHT_TIMEOUT_MINUTES * 60,
              volumes=MOUNTS, scaledown_window=2)
def preflight():
    """Three paid minutes that de-risk nine paid hours: builds the real model
    on the real data, compiles it, runs it, and reports measured tokens per
    second and peak memory. Nothing is saved."""
    sys.path.insert(0, TRAINING_DIR)
    require(f"{DATA_DIR}/train.bin", f"{DATA_DIR}/val.bin", f"{TOKENIZER_DIR}/tokenizer.json")

    import torch

    run_script("train.py", preflight_arguments())
    total_minutes = PRETRAIN_MINUTES[1] + PRETRAIN_MINUTES[2]
    print(f"\n[modal] peak VRAM {torch.cuda.max_memory_allocated()/1e9:.1f} GB of "
          f"{torch.cuda.get_device_properties(0).total_memory/1e9:.0f} GB", flush=True)
    print(f"[modal] take the steady-state tok/s printed above and multiply by {total_minutes*60:,} "
          f"seconds to get the tokens the full two-phase run will see", flush=True)


# ----------------------------------------------------------------------
# Stage 3: pretraining
# ----------------------------------------------------------------------

@app.function(image=image, gpu=GPU_STAGE["gpu"], cpu=GPU_STAGE["cpu"],
              memory=GPU_STAGE["memory_gib"] * 1024, timeout=PRETRAIN_TIMEOUT_MINUTES[1] * 60,
              volumes=MOUNTS, scaledown_window=2)
def pretrain_phase1(resume_from: str = "", minutes: float = 0.0,
                    schedule_start: float = -1.0, warmup_steps: int = 0):
    _pretrain(1, resume_from, minutes, schedule_start, warmup_steps)


@app.function(image=image, gpu=GPU_STAGE["gpu"], cpu=GPU_STAGE["cpu"],
              memory=GPU_STAGE["memory_gib"] * 1024, timeout=PRETRAIN_TIMEOUT_MINUTES[2] * 60,
              volumes=MOUNTS, scaledown_window=2)
def pretrain_phase2(resume_from: str = "", minutes: float = 0.0,
                    schedule_start: float = -1.0, warmup_steps: int = 0):
    _pretrain(2, resume_from, minutes, schedule_start, warmup_steps)


def _pretrain(phase, resume_from="", minutes=0.0, schedule_start=-1.0, warmup_steps=0):
    sys.path.insert(0, TRAINING_DIR)
    require(f"{DATA_DIR}/train.bin", f"{DATA_DIR}/val.bin", f"{TOKENIZER_DIR}/tokenizer.json")
    if is_done(f"pretrain_phase{phase}"):
        print(f"[modal] phase {phase} already finished; skipping", flush=True)
        return
    if phase == 2:
        require(f"{CHECKPOINT_DIR}/phase1_weights.pt")

    if resume_from:
        require(resume_from)
        print(f"[modal] resuming phase {phase} from {resume_from}", flush=True)
    arguments = pretrain_arguments(
        phase, resume_from=resume_from,
        minutes=minutes if minutes > 0 else None,
        schedule_start=schedule_start if schedule_start >= 0 else None,
        warmup_steps=warmup_steps if warmup_steps > 0 else None,
    )
    stop_committing = commit_periodically()
    try:
        run_script("train.py", arguments)
    finally:
        stop_committing()
        VOLUME.commit()

    mark_done(f"pretrain_phase{phase}", minutes=PRETRAIN_MINUTES[phase])
    if phase == 1:
        _export_weights_for_transfer()


def _export_weights_for_transfer():
    """Writes the bfloat16, optimizer-free copy of phase 1 that phase 2
    needs: ~1.5GB instead of ~9GB."""
    import torch

    import checkpoint_utils

    source = f"{CHECKPOINT_DIR}/base1_best.pt"
    if not os.path.exists(source):
        source = f"{CHECKPOINT_DIR}/base1_last.pt"
    require(source)
    checkpoint = checkpoint_utils._torch_load_tolerant(source, map_location="cpu", mmap=True)
    checkpoint_utils.save_checkpoint_atomically({
        "model": {key: value.to(torch.bfloat16) for key, value in checkpoint["model"].items()},
        "step": checkpoint.get("step", 0),
        "best_val": checkpoint.get("best_val", float("nan")),
        "model_config": checkpoint["model_config"],
        "inference_only": True,
    }, f"{CHECKPOINT_DIR}/phase1_weights.pt")
    VOLUME.commit()

    size_gb = os.path.getsize(f"{CHECKPOINT_DIR}/phase1_weights.pt") / 1e9
    transfer = ("tokenizer/tokenizer.json", "data/val.bin", "checkpoints/phase1_weights.pt")
    print(f"\n[cloud] PHASE 1 COMPLETE. Move these to phase 2 (~{size_gb:.2f} GB):", flush=True)
    print("  on the phase 1 machine:", flush=True)
    for path in transfer:
        print(f"    modal volume get llm-v2 {path} ./transfer/{os.path.basename(path)}", flush=True)
    print("  then on the phase 2 machine:", flush=True)
    for path in transfer:
        print(f"    modal volume put llm-v2 ./transfer/{os.path.basename(path)} {path}", flush=True)
    print("    modal run --detach cloud_run.py --stage phase2", flush=True)


# ----------------------------------------------------------------------
# Stage 4: chat tuning, samples, export
# ----------------------------------------------------------------------

@app.function(image=image, gpu=GPU_STAGE["gpu"], cpu=GPU_STAGE["cpu"],
              memory=GPU_STAGE["memory_gib"] * 1024, timeout=FINETUNE_TIMEOUT_MINUTES * 60,
              volumes=MOUNTS, scaledown_window=2)
def finetune():
    sys.path.insert(0, TRAINING_DIR)
    base = f"{CHECKPOINT_DIR}/base2_best.pt"
    if not os.path.exists(base):
        base = f"{CHECKPOINT_DIR}/base2_last.pt"
    require(base, f"{DATA_DIR}/sft_train_ids.npy")

    stop_committing = commit_periodically()
    try:
        run_script("sft_train.py", finetune_arguments(base))
    finally:
        stop_committing()
        VOLUME.commit()
    mark_done("finetune")
    _sample_replies()


def _sample_replies():
    """Prints real answers to a fixed set of prompts, so the run's own log
    shows whether the model actually chats."""
    chat_checkpoint = f"{CHECKPOINT_DIR}/chat_best.pt"
    if not os.path.exists(chat_checkpoint):
        chat_checkpoint = f"{CHECKPOINT_DIR}/chat_last.pt"
    prompts = ["hi", "what is your name?", "what is bitcoin?", "name two colours",
               "write a short poem about the moon", "how do I boil an egg?"]
    for prompt in prompts:
        print(f"\n=== {prompt}", flush=True)
        try:
            run_script("sample.py", ["--ckpt", chat_checkpoint, "--tokenizer-dir", TOKENIZER_DIR,
                                      "--chat", "--prompt", prompt, "--temperature", 0.0,
                                      "--max-new-tokens", 120])
        except RuntimeError as error:
            print(f"[modal] sampling failed: {error}", flush=True)


@app.function(image=image, cpu=CPU_STAGE["cpu"], memory=CPU_STAGE["memory_gib"] * 1024,
              timeout=EXPORT_TIMEOUT_MINUTES * 60, volumes=MOUNTS, scaledown_window=2)
def export():
    """Writes the small, inference-only checkpoint to download."""
    sys.path.insert(0, TRAINING_DIR)
    import checkpoint_utils

    source = f"{CHECKPOINT_DIR}/chat_best.pt"
    if not os.path.exists(source):
        source = f"{CHECKPOINT_DIR}/chat_last.pt"
    require(source)
    _, before, after = checkpoint_utils.strip_optimizer_state(
        source, destination_path=f"{CHECKPOINT_DIR}/chat_final.pt")
    VOLUME.commit()
    print(f"[modal] {os.path.basename(source)} {checkpoint_utils.format_bytes(before)} -> "
          f"chat_final.pt {checkpoint_utils.format_bytes(after)}", flush=True)
    print("\n[modal] download it with:\n"
          "    modal volume get llm-v2 checkpoints/chat_final.pt ../checkpoints/chat_final.pt\n"
          "  then chat locally with:\n"
          "    python server.py --checkpoint chat_final.pt", flush=True)


# ----------------------------------------------------------------------
# Orchestrators (remote, so a disconnected laptop cannot stop the run)
# ----------------------------------------------------------------------

@app.function(image=image, cpu=TINY_STAGE["cpu"], memory=TINY_STAGE["memory_gib"] * 1024,
              timeout=ORCHESTRATOR_TIMEOUT_MINUTES * 60, volumes=MOUNTS, scaledown_window=2)
def run_phase1():
    prepare_data.remote(1)
    pretrain_phase1.remote()


@app.function(image=image, cpu=TINY_STAGE["cpu"], memory=TINY_STAGE["memory_gib"] * 1024,
              timeout=ORCHESTRATOR_TIMEOUT_MINUTES * 60, volumes=MOUNTS, scaledown_window=2)
def run_phase2():
    prepare_data.remote(2)
    pretrain_phase2.remote()


@app.function(image=image, cpu=TINY_STAGE["cpu"], memory=TINY_STAGE["memory_gib"] * 1024,
              timeout=ORCHESTRATOR_TIMEOUT_MINUTES * 60, volumes=MOUNTS, scaledown_window=2)
def run_finetune():
    """The fine-tune-only stage. Expects checkpoints/base2_best.pt and
    tokenizer/tokenizer.json to have been uploaded with `modal volume put`."""
    require(f"{CHECKPOINT_DIR}/base2_best.pt", f"{TOKENIZER_DIR}/tokenizer.json")
    prepare_chat_data.remote()
    finetune.remote()
    export.remote()


@app.local_entrypoint()
def main(stage: str = "budget", spawn: bool = False, resume_from: str = "",
         minutes: float = 0.0, schedule_start: float = -1.0, warmup_steps: int = 0):
    print_budget()
    if stage == "budget":
        print("\n(nothing was run; pass --stage preflight | phase1 | phase2)")
        return

    remote_stages = {
        "preflight": preflight, "phase1": run_phase1, "phase2": run_phase2,
        "finetune": run_finetune, "prepare_chat": prepare_chat_data,
        "pretrain1": pretrain_phase1, "pretrain2": pretrain_phase2,
        "finetune": finetune, "export": export,
    }
    pretrain_kwargs = {}
    if stage in ("pretrain1", "pretrain2"):
        pretrain_kwargs = dict(resume_from=resume_from, minutes=minutes,
                               schedule_start=schedule_start, warmup_steps=warmup_steps)
    print(f"\nlaunching stage: {stage}\n")
    if stage == "prepare1":
        prepare_data.remote(1)
    elif stage == "prepare2":
        prepare_data.remote(2)
    elif stage in remote_stages:
        if spawn:
            # .spawn() starts the function and returns at once, so the launching terminal
            # can exit immediately. A blocking .remote() keeps a client connection open for
            # hours, and the job dies with whatever kills that client -- which is exactly
            # how the first attempt at phase 1 was lost, despite --detach.
            call = remote_stages[stage].spawn(**pretrain_kwargs)
            print(f"spawned {stage}: function call {call.object_id}")
            print("It now runs independently of this terminal. Follow it with:")
            print("    modal app logs llm-v2")
        else:
            remote_stages[stage].remote(**pretrain_kwargs)
    else:
        raise SystemExit(f"unknown stage {stage!r}; choose from "
                         f"{sorted(list(remote_stages) + ['prepare1', 'prepare2', 'budget'])}")
