"""
The training run, start to finish, on rented cloud GPUs.

Trains a 777M-parameter (161M active per token) DeepSeek-style Mixture-of-
Experts chat model from scratch on ~6B tokens, split into two pretraining
phases on separate machines and a third stage that fine-tunes.

    PHASE 1
        python verify_cloud_run.py                   # free: validate the whole plan
        modal run cloud_run.py --stage budget         # free: print the cost ceiling
        modal run cloud_run.py --stage preflight      # ~$0.35: measure real speed first
        modal run --detach cloud_run.py --stage phase1
        # then move three files across (the run prints the exact commands)

    PHASE 2
        modal run --detach cloud_run.py --stage phase2
        modal volume get llm-v2 checkpoints/chat_final.pt ../checkpoints/chat_final.pt

Why two phases. Phase 1 pretrains the first ~52% of the schedule; phase 2
continues it and then chat-tunes. The learning rate follows ONE cosine
curve across both phases (train.py's --schedule-start / --schedule-end), so
the model anneals properly at the very end instead of decaying to zero
halfway through and being re-warmed from scratch.

What crosses the boundary: the tokenizer (~6MB), the validation tokens
(~20MB) and the phase-1 weights in bfloat16 (~1.5GB). Optimizer state is NOT
carried across -- that would be a ~9GB transfer for a small quality gain --
so phase 2 starts a fresh AdamW and re-warms over 150 steps onto the same
curve.

Spending safety, in three layers:
  * Every function has a hard timeout. worst_case_by_phase() below multiplies
    those timeouts by the provider's published prices, and an assert at import
    time refuses to load this module if any phase could exceed its budget in
    PHASE_BUDGET_USD. A bad plan fails locally, before anything runs.
  * Every command line is built by a plain function (pretrain_arguments and
    friends) so verify_cloud_run.py can check each flag against the target
    script's parser. A typo in a flag is caught for free rather than on a
    rented H100.
  * Every stage writes a marker file on the volume, so re-running after a
    failure skips work that was already paid for.
"""
import json
import os
import subprocess
import sys
import threading
import time

import modal

HERE = os.path.dirname(os.path.abspath(__file__))

# ----------------------------------------------------------------------
# The plan
# ----------------------------------------------------------------------

MODEL_SIZE = "chat"          # the preset in config.py: 777M total / 161M active, 32 routed experts
BLOCK_SIZE = 1024            # must equal that preset's max_sequence_length
VOCAB_SIZE = 32768           # a 65k vocabulary would spend ~18% of every step in the output layer alone

# FineWeb-Edu ships as 14 parquet shards of ~2.15GB, each roughly 0.8B tokens at this vocabulary
# size. Phase 2 reads DIFFERENT shards, so no text is ever seen twice.
FINEWEB_REPO = "HuggingFaceFW/fineweb-edu"
# Measured on the preflight: 179k tokens/s, so phase 2 will consume ~2.65B tokens in its
# 252 minutes. Three shards (~2.25B) would mean repeating data, so phase 2 reads four.
FINEWEB_SHARDS = {1: (0, 1, 2), 2: (3, 4, 5, 6, 7)}
TOKENIZER_SAMPLE_BYTES = 1_500_000_000   # text used to train the byte-level BPE tokenizer

CHAT_DATASET = "HuggingFaceTB/smol-smoltalk"          # built specifically for 135M-360M models
CHAT_EXTRA_DATASET = ("HuggingFaceTB/smoltalk", "everyday-conversations")
# Measured after the first chat tune: at x3 the everyday-conversations subset was only ~1.5%
# of packed rows, and the model answered a bare "hi" with a lecture on quantum mechanics.
# x25 brings small talk to roughly 12% of rows.
CHAT_EXTRA_REPEATS = 25

# Conversations generated by persona_data.py: who built the model, what it is, what it
# cannot do, and the pattern that answers "what is my name?" with "YOUR name is ...".
# None of this exists in any public dataset, and none of it can be learned from more
# pretraining, so it has to be written and mixed in here.
# 140k sessions pack into ~12.7k rows: 3.3% of the chat set, seen about 2.7 times over
# the run. The first attempt used 20k single exchanges, which packed to 0.18% -- far too
# little to teach anything, and raising it by repetition would have taught parroting.
PERSONA_CONVERSATIONS = 140_000

PRETRAIN_MINUTES = {1: 276, 2: 340}
PRETRAIN_TIMEOUT_MINUTES = {1: 300, 2: 358}
# PINNED, not derived from the minutes above. Phase 1 already ran with schedule-end
# 0.5227, so this is where its learning rate actually stopped. Recomputing the split
# after lengthening phase 2 would start phase 2 lower on the curve than phase 1 ended,
# i.e. the learning rate would jump back UP mid-training.
SCHEDULE_SPLIT = 0.5227272727272727

# The third stage exists only to fine-tune. One long run beats two short ones: the
# cosine schedule completes once instead of restarting, and the ~$0.35 of container
# startup is paid once. 85 minutes is ~1.9 passes over the packed chat data.
FINETUNE_MINUTES = 80
FINETUNE_TIMEOUT_MINUTES = 88

MICRO_BATCH_SIZE = 24        # sequences resident at once: ~24k tokens per micro-batch
GRAD_ACCUM = 12              # -> 294,912 tokens per optimizer step
