"""
The training run, start to finish, on rented cloud GPUs.

Trains a 777M-parameter (161M active per token) DeepSeek-style Mixture-of-
Experts chat model from scratch on ~6B tokens, split into two pretraining
phases on separate machines and a third stage that fine-tunes.

    PHASE 1
        python verify_cloud_run.py                   # free: validate the whole plan
        modal run cloud_run.py --stage budget         # free: print the cost ceiling
        modal run cloud_run.py --stage preflight      # ~$0.35: measure real speed first
        modal run --detach cloud_run.py --stage phase1
        # then move three files across (the run prints the exact commands)

    PHASE 2
        modal run --detach cloud_run.py --stage phase2
        modal volume get llm-v2 checkpoints/chat_final.pt ../checkpoints/chat_final.pt

Why two phases. Phase 1 pretrains the first ~52% of the schedule; phase 2
continues it and then chat-tunes. The learning rate follows ONE cosine
curve across both phases (train.py's --schedule-start / --schedule-end), so
the model anneals properly at the very end instead of decaying to zero
halfway through and being re-warmed from scratch.

What crosses the boundary: the tokenizer (~6MB), the validation tokens
(~20MB) and the phase-1 weights in bfloat16 (~1.5GB). Optimizer state is NOT
carried across -- that would be a ~9GB transfer for a small quality gain --
so phase 2 starts a fresh AdamW and re-warms over 150 steps onto the same
curve.

Spending safety, in three layers:
  * Every function has a hard timeout. worst_case_by_phase() below multiplies
    those timeouts by the provider's published prices, and an assert at import
    time refuses to load this module if any phase could exceed its budget in
    PHASE_BUDGET_USD. A bad plan fails locally, before anything runs.
  * Every command line is built by a plain function (pretrain_arguments and
    friends) so verify_cloud_run.py can check each flag against the target
    script's parser. A typo in a flag is caught for free rather than on a
    rented H100.
  * Every stage writes a marker file on the volume, so re-running after a
    failure skips work that was already paid for.
"""
import json
import os
import subprocess
import sys
import threading
import time

import modal

HERE = os.path.dirname(os.path.abspath(__file__))

# ----------------------------------------------------------------------
# The plan
# ----------------------------------------------------------------------

MODEL_SIZE = "chat"          # the preset in config.py: 777M total / 161M active, 32 routed experts
BLOCK_SIZE = 1024            # must equal that preset's max_sequence_length
VOCAB_SIZE = 32768           # a 65k vocabulary would spend ~18% of every step in the output layer alone

# FineWeb-Edu ships as 14 parquet shards of ~2.15GB, each roughly 0.8B tokens at this vocabulary
# size. Phase 2 reads DIFFERENT shards, so no text is ever seen twice.
FINEWEB_REPO = "HuggingFaceFW/fineweb-edu"
# Measured on the preflight: 179k tokens/s, so phase 2 will consume ~2.65B tokens in its
# 252 minutes. Three shards (~2.25B) would mean repeating data, so phase 2 reads four.
FINEWEB_SHARDS = {1: (0, 1, 2), 2: (3, 4, 5, 6, 7)}
TOKENIZER_SAMPLE_BYTES = 1_500_000_000   # text used to train the byte-level BPE tokenizer

CHAT_DATASET = "HuggingFaceTB/smol-smoltalk"          # built specifically for 135M-360M models
CHAT_EXTRA_DATASET = ("HuggingFaceTB/smoltalk", "everyday-conversations")
# Measured after the first chat tune: at x3 the everyday-conversations subset was only ~1.5%
# of packed rows, and the model answered a bare "hi" with a lecture on quantum mechanics.
# x25 brings small talk to roughly 12% of rows.
CHAT_EXTRA_REPEATS = 25

# Conversations generated by persona_data.py: who built the model, what it is, what it
# cannot do, and the pattern that answers "what is my name?" with "YOUR name is ...".
# None of this exists in any public dataset, and none of it can be learned from more
# pretraining, so it has to be written and mixed in here.
# 140k sessions pack into ~12.7k rows: 3.3% of the chat set, seen about 2.7 times over
# the run. The first attempt used 20k single exchanges, which packed to 0.18% -- far too
# little to teach anything, and raising it by repetition would have taught parroting.
PERSONA_CONVERSATIONS = 140_000

PRETRAIN_MINUTES = {1: 276, 2: 340}
PRETRAIN_TIMEOUT_MINUTES = {1: 300, 2: 358}
# PINNED, not derived from the minutes above. Phase 1 already ran with schedule-end
# 0.5227, so this is where its learning rate actually stopped. Recomputing the split
# after lengthening phase 2 would start phase 2 lower on the curve than phase 1 ended,
# i.e. the learning rate would jump back UP mid-training.
SCHEDULE_SPLIT = 0.5227272727272727

# The third stage exists only to fine-tune. One long run beats two short ones: the
# cosine schedule completes once instead of restarting, and the ~$0.35 of container
# startup is paid once. 85 minutes is ~1.9 passes over the packed chat data.
FINETUNE_MINUTES = 80
FINETUNE_TIMEOUT_MINUTES = 88

MICRO_BATCH_SIZE = 24        # sequences resident at once: ~24k tokens per micro-batch
GRAD_ACCUM = 12              # -> 294,912 tokens per optimizer step
MAX_LEARNING_RATE = 6e-4
MIN_LEARNING_RATE = 6e-5
WARMUP_STEPS = {1: 300, 2: 150}   # phase 2 only needs a short re-warm for its fresh optimizer

FINETUNE_MICRO_BATCH = 24
FINETUNE_GRAD_ACCUM = 3
FINETUNE_MAX_LR = 2e-4
FINETUNE_MIN_LR = 2e-5

# ----------------------------------------------------------------------
# Budget
# ----------------------------------------------------------------------

# What each phase is allowed to spend. Phases 1 and 2 are finished and came in under
# budget; phase 3 is the fine-tune, and its figure is what was left after roughly $0.70
# went on a first launch that was stopped early once the persona mix was found to be too
# small. Every timeout below is sized against these, and the assert underneath refuses to
# import the module if a plan could exceed one.
PHASE_BUDGET_USD = {1: 30.0, 2: 30.0, 3: 7.80}
PRICE_PER_SECOND = {"H100": 0.001097, "cpu_core": 0.0000131, "memory_gib": 0.00000222}

CPU_STAGE = dict(cpu=16, memory_gib=32, gpu=None)
GPU_STAGE = dict(cpu=4, memory_gib=32, gpu="H100")
TINY_STAGE = dict(cpu=0.125, memory_gib=1, gpu=None)

PREPARE_TIMEOUT_MINUTES = 60
# Chat-only preparation skips the FineWeb download and tokenizer training, so it needs
# far less wall clock -- and on the fine-tune phase every minute of timeout is budget.
CHAT_PREPARE_TIMEOUT_MINUTES = 25
PREFLIGHT_TIMEOUT_MINUTES = 10
EXPORT_TIMEOUT_MINUTES = 15
# must exceed the WHOLE phase-2 chain: data prep + pretrain + chat tuning + export,
# or the orchestrator is killed before it can launch the later stages
ORCHESTRATOR_TIMEOUT_MINUTES = 500


def stage_cost_per_second(stage):
    gpu_price = PRICE_PER_SECOND[stage["gpu"]] if stage["gpu"] else 0.0
    return (gpu_price + stage["cpu"] * PRICE_PER_SECOND["cpu_core"]
            + stage["memory_gib"] * PRICE_PER_SECOND["memory_gib"])


def worst_case_by_phase():
    """The most each phase can possibly be charged: every stage running to
    its full Modal timeout."""
    prepare = stage_cost_per_second(CPU_STAGE) * PREPARE_TIMEOUT_MINUTES * 60
    chat_prepare = stage_cost_per_second(CPU_STAGE) * CHAT_PREPARE_TIMEOUT_MINUTES * 60
    preflight_cost = stage_cost_per_second(GPU_STAGE) * PREFLIGHT_TIMEOUT_MINUTES * 60
    export_cost = stage_cost_per_second(CPU_STAGE) * EXPORT_TIMEOUT_MINUTES * 60
    orchestrator = stage_cost_per_second(TINY_STAGE) * ORCHESTRATOR_TIMEOUT_MINUTES * 60
    pretrain = {phase: stage_cost_per_second(GPU_STAGE) * PRETRAIN_TIMEOUT_MINUTES[phase] * 60 for phase in (1, 2)}
    finetune_cost = stage_cost_per_second(GPU_STAGE) * FINETUNE_TIMEOUT_MINUTES * 60
    return {
        1: {"data prep": prepare, "preflight": preflight_cost, "pretrain phase 1": pretrain[1],
            "orchestrator": orchestrator},
        2: {"data prep": prepare, "pretrain phase 2": pretrain[2],
            "export": export_cost, "orchestrator": orchestrator},
        3: {"chat data prep": chat_prepare, "chat tuning": finetune_cost,
            "export": export_cost, "orchestrator": orchestrator},
    }


def print_budget():
    print("\nWORST CASE per phase (every stage hitting its full timeout)")
    for phase, stages in worst_case_by_phase().items():
        print(f"  phase {phase} (budget ${PHASE_BUDGET_USD[phase]:.2f}):")
        for name, cost in stages.items():
            print(f"    {name:<20s} ${cost:6.2f}")
        print(f"    {'TOTAL':<20s} ${sum(stages.values()):6.2f}")
    expected = {
        1: 0.45 + 0.30 + stage_cost_per_second(GPU_STAGE) * (PRETRAIN_MINUTES[1] + 8) * 60 + 0.03,
        2: 0.40 + stage_cost_per_second(GPU_STAGE) * (PRETRAIN_MINUTES[2] + 8) * 60 + 0.10,
        3: 0.20 + stage_cost_per_second(GPU_STAGE) * (FINETUNE_MINUTES + 6) * 60 + 0.10,
    }
    print("\n  EXPECTED: " + ", ".join(f"phase {phase} ~${cost:.2f}"
                                       for phase, cost in expected.items())
          + f", total ~${sum(expected.values()):.2f}")


for _phase, _stages in worst_case_by_phase().items():
    assert sum(_stages.values()) <= PHASE_BUDGET_USD[_phase], (
        f"phase {_phase} could be charged ${sum(_stages.values()):.2f}, over its "
        f"${PHASE_BUDGET_USD[_phase]:.2f} budget -- lower a timeout before running anything")

# ----------------------------------------------------------------------
# Modal setup
# ----------------------------------------------------------------------

app = modal.App("llm-v2")

image = (
    modal.Image.debian_slim(python_version="3.11")
    .pip_install("torch==2.6.0", "numpy", "tokenizers", "datasets", "pyarrow",
                 "huggingface_hub", "hf_transfer")
    .env({"HF_HUB_ENABLE_HF_TRANSFER": "1", "KMP_DUPLICATE_LIB_OK": "TRUE", "PYTHONUNBUFFERED": "1"})
    .add_local_dir(HERE, remote_path="/root/training",
                   ignore=["__pycache__", "*.pyc", "db", "static", "*.jsonl", "*.txt", "*.md"])
)

VOLUME = modal.Volume.from_name("llm-v2", create_if_missing=True)
MOUNTS = {"/vol": VOLUME}

DATA_DIR = "/vol/data"
TOKENIZER_DIR = "/vol/tokenizer"
CHECKPOINT_DIR = "/vol/checkpoints"
MARKER_DIR = "/vol/markers"
TRAINING_DIR = "/root/training"

# ----------------------------------------------------------------------
# Command lines, as data so they can be validated without running anything
# ----------------------------------------------------------------------

def pretrain_arguments(phase, data_dir=DATA_DIR, tokenizer_dir=TOKENIZER_DIR, checkpoint_dir=CHECKPOINT_DIR,
                       resume_from="", minutes=None, schedule_start=None, warmup_steps=None):
    """The exact train.py command line for one pretraining phase.

    The override parameters exist for restarting an interrupted phase. A run
    that stopped a third of the way through must not restart the learning-rate
    curve from the beginning: pass the minutes that remain and the point on the
    curve it had already reached, and the schedule carries on from there."""
    arguments = [
        "--size", MODEL_SIZE, "--tag", f"base{phase}", "--data-dir", data_dir,
        "--tokenizer-dir", tokenizer_dir, "--ckpt-dir", checkpoint_dir,
        "--minutes", PRETRAIN_MINUTES[phase] if minutes is None else minutes,
        "--lr-schedule", "time",
        "--schedule-start", (0.0 if phase == 1 else SCHEDULE_SPLIT) if schedule_start is None else schedule_start,
        "--schedule-end", SCHEDULE_SPLIT if phase == 1 else 1.0,
        "--micro-batch-size", MICRO_BATCH_SIZE, "--grad-accum", GRAD_ACCUM,
        "--max-lr", MAX_LEARNING_RATE, "--min-lr", MIN_LEARNING_RATE,
        "--warmup-steps", WARMUP_STEPS[phase] if warmup_steps is None else warmup_steps,
        "--eval-interval", 500, "--eval-iters", 20, "--checkpoint-interval", 1000,
    ]
    if resume_from:
        # continues the SAME run: optimizer moments, step counter and best-so-far restored
        arguments += ["--resume", resume_from]
    elif phase == 2:
        # weights only: phase 1's optimizer state stays behind on the other machine
        arguments += ["--init-from", f"{checkpoint_dir}/phase1_weights.pt"]
    return arguments


def preflight_arguments(data_dir=DATA_DIR, tokenizer_dir=TOKENIZER_DIR):
    """A three-minute version of the real thing: same model, same data, same
    batch shape, nothing saved."""
    return [
        "--size", MODEL_SIZE, "--tag", "preflight", "--data-dir", data_dir,
        "--tokenizer-dir", tokenizer_dir, "--ckpt-dir", "/tmp/preflight",
        "--minutes", 3.0, "--lr-schedule", "time",
        "--micro-batch-size", MICRO_BATCH_SIZE, "--grad-accum", GRAD_ACCUM,
        "--max-lr", MAX_LEARNING_RATE, "--min-lr", MIN_LEARNING_RATE, "--warmup-steps", 50,
        "--eval-interval", 10 ** 9, "--checkpoint-interval", 10 ** 9, "--log-interval", 5,
    ]


def finetune_arguments(base_checkpoint, data_dir=DATA_DIR, checkpoint_dir=CHECKPOINT_DIR):
    return [
        "--init-from", base_checkpoint, "--data-dir", data_dir, "--ckpt-dir", checkpoint_dir,
        "--tag", "chat", "--minutes", FINETUNE_MINUTES, "--lr-schedule", "time", "--epochs", 3.0,
        "--batch-size", FINETUNE_MICRO_BATCH, "--grad-accum", FINETUNE_GRAD_ACCUM,
        "--max-lr", FINETUNE_MAX_LR, "--min-lr", FINETUNE_MIN_LR, "--warmup-steps", 100,
        "--eval-interval", 200, "--eval-iters", 10, "--checkpoint-interval", 400,
    ]


# ----------------------------------------------------------------------
# Small helpers used inside the containers
# ----------------------------------------------------------------------

def marker_path(name):
    return os.path.join(MARKER_DIR, f"{name}.json")


def is_done(name):
    return os.path.exists(marker_path(name))


def mark_done(name, **details):
    os.makedirs(MARKER_DIR, exist_ok=True)
    with open(marker_path(name), "w", encoding="utf-8") as handle:
        json.dump({"finished_at": time.strftime("%Y-%m-%d %H:%M:%S"), **details}, handle, indent=2)
    VOLUME.commit()


def commit_periodically(interval_seconds=300):
    """Commits the volume on a timer; returns a function that stops it.

    Checkpoints written mid-run only become durable once the volume is
    committed. Without this, a run that times out or crashes at hour four
    leaves the volume exactly as it was at hour zero."""
    stop_event = threading.Event()

    def loop():
        while not stop_event.wait(interval_seconds):
            try:
                VOLUME.commit()
                print(f"[modal] volume committed at {time.strftime('%H:%M:%S')}", flush=True)
            except Exception as error:
                print(f"[modal] commit failed: {error}", flush=True)

    threading.Thread(target=loop, daemon=True).start()
    return stop_event.set
