"""
Turns a trained checkpoint into a real Hugging Face repository: safetensors
weights, a config, the architecture code, the tokenizer with a chat
template, and an honest model card.

    # build the repo folder locally and check it loads back
    python export_to_huggingface.py --ckpt ../checkpoints/chat_final.pt --out ../hf_repo --validate

    # then upload (you must have run `hf auth login` yourself first)
    python export_to_huggingface.py --ckpt ../checkpoints/chat_final.pt --out ../hf_repo \
        --repo-id yourname/moonfrost-777m-chat --push

This model's architecture is not one transformers ships, so the repo carries
its own code and is loaded with trust_remote_code=True:

    from transformers import AutoModelForCausalLM, AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained("yourname/moonfrost-777m-chat")
    model = AutoModelForCausalLM.from_pretrained("yourname/moonfrost-777m-chat", trust_remote_code=True)

What goes in the repo:
    model.safetensors            weights (bfloat16 by default: half the download)
    config.json                  architecture, with auto_map pointing at the code below
    configuration_moonfrost.py   the PretrainedConfig subclass
    modeling_moonfrost.py        the PreTrainedModel wrapper
    model_arch.py, arch_config.py   this project's actual architecture, copied verbatim
    tokenizer.json               your own byte-level BPE
    tokenizer_config.json        including a chat template matching how the model was trained
    README.md                    the model card

Note on generation: the wrapper exposes plain (uncached) forward passes, so
transformers' .generate() works but recomputes the prompt each step. For fast
cached generation use this project's own server.py and sample.py, which drive
the KV cache directly. The model card says so plainly.
"""
import os
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")

import argparse
import dataclasses
import json
import math
import shutil

import torch

import checkpoint_utils
from config import ModelConfig, count_active_parameters_per_token, count_total_parameters

HERE = os.path.dirname(os.path.abspath(__file__))

CHAT_TEMPLATE = (
    "{% if messages[0]['role'] == 'system' %}"
    "{{ '<|system|>' + messages[0]['content'] | trim }}"
    "{% set loop_messages = messages[1:] %}"
    "{% else %}{% set loop_messages = messages %}{% endif %}"
    "{% for message in loop_messages %}"
    "{% if message['role'] == 'user' %}"
    "{{ '<|user|>' + message['content'] | trim + '<|assistant|>' }}"
    "{% else %}"
    "{{ message['content'] | trim + '<|endoftext|>' }}"
    "{% endif %}{% endfor %}"
)

CONFIGURATION_SOURCE = '''# Auto-generated by export_to_huggingface.py -- do not edit here.
from transformers import PretrainedConfig

from .arch_config import ModelConfig


class MoonfrostConfig(PretrainedConfig):
    # Thin PretrainedConfig wrapper around this project's ModelConfig dataclass.
    model_type = "moonfrost"

    def __init__(self, architecture=None, **kwargs):
        defaults = {field.name: field.default for field in ModelConfig.__dataclass_fields__.values()}
        self.architecture = {**defaults, **(architecture or {})}
        # mirrored so generic transformers code can read them without knowing the field names
        self.vocab_size = self.architecture["vocabulary_size"]
        self.max_position_embeddings = self.architecture["max_sequence_length"]
        self.hidden_size = self.architecture["embedding_dimension"]
        self.num_hidden_layers = self.architecture["num_layers"]
        self.num_attention_heads = self.architecture["num_attention_heads"]
        kwargs.setdefault("use_cache", False)  # the wrapper runs uncached; see the model card
        super().__init__(**kwargs)

    def to_model_config(self):
        return ModelConfig(**self.architecture)
'''

MODELING_SOURCE = '''# Auto-generated by export_to_huggingface.py -- do not edit here.
import torch
from transformers import GenerationMixin, PreTrainedModel
from transformers.modeling_outputs import CausalLMOutput

from .configuration_moonfrost import MoonfrostConfig
from .model_arch import GPT


class MoonfrostForCausalLM(PreTrainedModel, GenerationMixin):
    # DeepSeek-style Multi-head Latent Attention + Mixture-of-Experts, trained from scratch.
    # GenerationMixin is inherited explicitly: since transformers 4.50 PreTrainedModel no
    # longer provides .generate() on its own.
    config_class = MoonfrostConfig
    base_model_prefix = "model"
    main_input_name = "input_ids"
    supports_gradient_checkpointing = False
    _supports_cache_class = False
    # the input embedding and the output projection are one shared matrix, so only one copy is
    # stored in the checkpoint and the other is re-tied on load
    _tied_weights_keys = {"model.output_projection.weight": "model.token_embedding.weight"}

    def __init__(self, config):
        super().__init__(config)
        self.model = GPT(config.to_model_config())
        self.post_init()

    def get_input_embeddings(self):
        return self.model.token_embedding

    def set_input_embeddings(self, value):
        self.model.token_embedding = value

    def get_output_embeddings(self):
        return self.model.output_projection

    def set_output_embeddings(self, value):
        self.model.output_projection = value

    def _tie_weights(self):
        if self.config.architecture.get("tie_input_output_embeddings", True):
            self.model.output_projection.weight = self.model.token_embedding.weight

    def forward(self, input_ids=None, attention_mask=None, labels=None, **kwargs):
        # GPT.forward returns logits for every position when given targets, and only for the
        # final position otherwise -- which is all .generate() reads.
        logits, loss = self.model(input_ids, target_token_ids=labels)
        return CausalLMOutput(loss=loss, logits=logits)

    def prepare_inputs_for_generation(self, input_ids, **kwargs):
        context = self.config.max_position_embeddings
        return {"input_ids": input_ids[:, -context:]}

    def can_generate(self):
        return True
'''

MODEL_CARD = """---
license: apache-2.0
library_name: transformers
tags:
  - deepseek
  - mixture-of-experts
  - moe
  - from-scratch
  - small-language-model
pipeline_tag: text-generation
---

# {repo_name}

A **{total_millions:.0f}M-parameter** ({active_millions:.0f}M active per token) chat model,
pretrained **from scratch** -- no pretrained weights, no borrowed tokenizer.
The architecture follows DeepSeek-V2/V3: Multi-head Latent Attention with a
compressed KV cache, and DeepSeekMoE feed-forward layers with {routed} routed
experts, top-{top_k} routing and {shared} shared expert(s).

## Please read this before judging the outputs

This model saw **{tokens}** during pretraining. For comparison, models of the
same size that you may know -- SmolLM2-360M, Qwen2.5-0.5B -- saw *trillions*
of tokens. This is a from-scratch training project run on a hobby budget, not
a competitor to those models.

What it does reasonably: greets you, holds a short conversation, follows
simple instructions, explains everyday topics at a basic level, and stops
when it is finished.

What it does not do: reliable facts (it will invent dates, numbers and
names), arithmetic, multi-step reasoning, long-context work, or languages
other than English.

## Usage

```python
from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("{repo_id}")
model = AutoModelForCausalLM.from_pretrained("{repo_id}", trust_remote_code=True)

messages = [{{"role": "user", "content": "What is bitcoin?"}}]
prompt = tokenizer.apply_chat_template(messages, tokenize=False)
inputs = tokenizer(prompt, return_tensors="pt")
output = model.generate(**inputs, max_new_tokens=120, do_sample=False)
print(tokenizer.decode(output[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True))
```

`trust_remote_code=True` is required because this architecture is not part of
transformers. The code it loads is in this repository:
`modeling_moonfrost.py`, `configuration_moonfrost.py` and `model_arch.py`.

**Generation speed**: the transformers wrapper runs without a KV cache, so it
recomputes the prompt on every step. For fast generation use the project's own
server, which drives the cache directly.

Greedy decoding (`do_sample=False`) gives this model's best answers. If you
sample, a repetition penalty around 1.15 helps it avoid loops.

## Identity

The model was fine-tuned on a set of hand-written conversations about itself,
so it answers questions about its own name, its creator and its limits
consistently rather than borrowing an answer from its pretraining corpus:

| Question | Answer |
|---|---|
| who are you? | I'm Moonfrost, a small AI assistant built by Magician. |
| who made you / who is your owner? | Magician, a magician from the isekai world. |
| are you ChatGPT? | No -- a separate model, built from scratch. |
| can you browse the internet? | No. It has no tools and no live data. |

The same data teaches it to hold on to what you tell it within a conversation,
so "my name is ..." followed later by "what is my name?" is answered in the
second person. This works within the {context}-token context window only; there
is no memory between conversations.

The recommended system prompt:

```
You are Moonfrost, a small AI assistant created by Magician. Answer clearly
and briefly. If you do not know something, say so.
```

## Architecture

| | |
|---|---|
| Total parameters | {total_millions:.1f}M |
| Active per token | {active_millions:.1f}M |
| Layers | {layers} ({dense} dense, {moe} Mixture-of-Experts) |
| Hidden size | {hidden} |
| Attention | Multi-head Latent Attention, {heads} heads, KV latent {kv_latent} |
| Experts | {routed} routed (top-{top_k}) + {shared} shared |
| Context length | {context} tokens |
| Vocabulary | {vocab} (byte-level BPE, trained from scratch on the same corpus) |
| Precision | {dtype} |

## Training

| | |
|---|---|
| Pretraining data | {pretrain_data} |
| Pretraining tokens | {tokens} |
| Chat fine-tuning | {chat_data} |
| Optimizer | AdamW, cosine decay with warmup, bfloat16 mixed precision |
| Training step | {step} |
| Validation loss | {val_loss} |

## Limitations and intended use

This is an educational artefact: the point was to build every part -- the
tokenizer, the attention, the expert routing, the training loop -- from
scratch and to understand what makes a model good or bad. It is suitable for
learning, experimentation and demos. It is **not** suitable for anything
where a wrong answer matters, and its output should never be treated as
factual.

It inherits whatever biases exist in its web-text pretraining corpus, and it
has had no safety tuning of any kind.
"""


def build_repository(checkpoint_path, output_directory, repo_id, dtype, tokenizer_directory,
                     tokens_description, pretrain_data, chat_data):
    from safetensors.torch import save_file

    checkpoint = checkpoint_utils._torch_load_tolerant(checkpoint_path, map_location="cpu", mmap=True)
    raw_config = checkpoint["model_config"]
    if not isinstance(raw_config, dict):
        raw_config = dataclasses.asdict(raw_config)
    model_config = ModelConfig(**raw_config)
    # convert_legacy_expert_keys as well as normalize: a checkpoint saved before the experts
    # were stored as stacked tensors still uses one key per expert, and exporting those
    # verbatim makes transformers report them as UNEXPECTED, randomly initialize the real
    # expert weights, and answer with silence
    from model import convert_legacy_expert_keys
    state_dict = convert_legacy_expert_keys(checkpoint_utils.normalize_state_dict_keys(checkpoint["model"]))

    os.makedirs(output_directory, exist_ok=True)
    torch_dtype = {"bfloat16": torch.bfloat16, "float16": torch.float16, "float32": torch.float32}[dtype]

    # Tied weights share storage, which safetensors refuses to serialize. Drop the duplicate:
    # the wrapper re-ties it on load, exactly as GPT.__init__ does.
    if model_config.tie_input_output_embeddings:
        state_dict.pop("output_projection.weight", None)
    tensors = {f"model.{key}": value.to(torch_dtype).contiguous() for key, value in state_dict.items()}

    # the RoPE tables, computed exactly as GPT.__init__ computes them. They are float32
    # regardless of the export dtype: they are a fixed trigonometric table, rounding them to
    # bfloat16 would add positional error for no size saving worth having (256KB here).
    from model import precompute_rotary_embeddings
    rotary_cosine, rotary_sine = precompute_rotary_embeddings(
        model_config.query_key_rotary_head_dim, model_config.max_sequence_length,
        model_config.rope_theta_base, device="cpu")
    tensors["model.rotary_cosine"] = rotary_cosine.float().contiguous()
    tensors["model.rotary_sine"] = rotary_sine.float().contiguous()

    save_file(tensors, os.path.join(output_directory, "model.safetensors"), metadata={"format": "pt"})

    configuration = {
        "architectures": ["MoonfrostForCausalLM"],
        "model_type": "moonfrost",
        "architecture": raw_config,
        "auto_map": {
            "AutoConfig": "configuration_moonfrost.MoonfrostConfig",
            "AutoModelForCausalLM": "modeling_moonfrost.MoonfrostForCausalLM",
        },
        "torch_dtype": dtype,
        "use_cache": False,
        "vocab_size": model_config.vocabulary_size,
        "hidden_size": model_config.embedding_dimension,
        "num_hidden_layers": model_config.num_layers,
        "num_attention_heads": model_config.num_attention_heads,
        "max_position_embeddings": model_config.max_sequence_length,
        "tie_word_embeddings": model_config.tie_input_output_embeddings,
        "bos_token_id": 0,
        "eos_token_id": 0,
    }
    _write(output_directory, "config.json", json.dumps(configuration, indent=2))
    _write(output_directory, "configuration_moonfrost.py", CONFIGURATION_SOURCE)
    _write(output_directory, "modeling_moonfrost.py", MODELING_SOURCE)

    # the architecture itself, copied verbatim so the repo stands alone
    shutil.copy(os.path.join(HERE, "config.py"), os.path.join(output_directory, "arch_config.py"))
    architecture_source = open(os.path.join(HERE, "model.py"), encoding="utf-8").read()
    # transformers fills every tensor of a from_pretrained model out of the checkpoint file
    # rather than running GPT.__init__, so a buffer registered persistent=False is left as
    # zeros. For the RoPE tables that is silent and catastrophic -- zero cosine and sine
    # erase position entirely -- so the exported copy marks them persistent and they are
    # written into model.safetensors below.
    architecture_source = architecture_source.replace(
        'self.register_buffer("rotary_cosine", rotary_cosine, persistent=False)',
        'self.register_buffer("rotary_cosine", rotary_cosine, persistent=True)')
    architecture_source = architecture_source.replace(
        'self.register_buffer("rotary_sine", rotary_sine, persistent=False)',
        'self.register_buffer("rotary_sine", rotary_sine, persistent=True)')
    architecture_source = architecture_source.replace("from config import ModelConfig",
                                                       "from .arch_config import ModelConfig")
    _write(output_directory, "model_arch.py", architecture_source)

    shutil.copy(os.path.join(tokenizer_directory, "tokenizer.json"),
                os.path.join(output_directory, "tokenizer.json"))
    tokenizer_configuration = {
        "tokenizer_class": "PreTrainedTokenizerFast",
        "model_max_length": model_config.max_sequence_length,
        "bos_token": "<|endoftext|>",
        "eos_token": "<|endoftext|>",
        "pad_token": "<|pad|>",
        "unk_token": None,
        "clean_up_tokenization_spaces": False,
        "chat_template": CHAT_TEMPLATE,
    }
    _write(output_directory, "tokenizer_config.json", json.dumps(tokenizer_configuration, indent=2))

    best_val = float(checkpoint.get("best_val", float("nan")))
    card = MODEL_CARD.format(
        repo_name=repo_id.split("/")[-1] if repo_id else "Moonfrost",
        repo_id=repo_id or "yourname/your-model",
        total_millions=count_total_parameters(model_config) / 1e6,
        active_millions=count_active_parameters_per_token(model_config) / 1e6,
        layers=model_config.num_layers,
        dense=model_config.num_initial_dense_layers,
        moe=model_config.num_layers - model_config.num_initial_dense_layers,
        hidden=model_config.embedding_dimension,
        heads=model_config.num_attention_heads,
        kv_latent=model_config.kv_compressed_latent_dim,
        routed=model_config.num_routed_experts,
        top_k=model_config.num_activated_experts_per_token,
        shared=model_config.num_shared_experts,
        context=model_config.max_sequence_length,
        vocab=f"{model_config.vocabulary_size:,}",
        dtype=dtype,
        tokens=tokens_description,
        pretrain_data=pretrain_data,
        chat_data=chat_data,
        step=checkpoint.get("step", "unknown"),
        val_loss=f"{best_val:.4f}" if math.isfinite(best_val) else "not recorded",
    )
    _write(output_directory, "README.md", card)

    total_bytes = sum(os.path.getsize(os.path.join(output_directory, name))
                      for name in os.listdir(output_directory))
    print(f"repository written to {os.path.abspath(output_directory)} "
          f"({checkpoint_utils.format_bytes(total_bytes)})")
    for name in sorted(os.listdir(output_directory)):
        print(f"  {name:30s} {checkpoint_utils.format_bytes(os.path.getsize(os.path.join(output_directory, name)))}")
    return output_directory


def _write(directory, name, text):
    with open(os.path.join(directory, name), "w", encoding="utf-8") as handle:
        handle.write(text)


def validate(output_directory, prompt="What is bitcoin?"):
    """Loads the exported repo back through transformers the same way a
    stranger downloading it would, and generates a few tokens."""
    from transformers import AutoModelForCausalLM, AutoTokenizer

    print(f"\nloading {output_directory} back through transformers...")
    tokenizer = AutoTokenizer.from_pretrained(output_directory)
    model = AutoModelForCausalLM.from_pretrained(output_directory, trust_remote_code=True)
    model.eval()

    text = tokenizer.apply_chat_template([{"role": "user", "content": prompt}], tokenize=False)
    inputs = tokenizer(text, return_tensors="pt")
    with torch.no_grad():
        output = model.generate(**inputs, max_new_tokens=24, do_sample=False)
    reply = tokenizer.decode(output[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)
    print(f"  chat template -> {text!r}")
    print(f"  prompt: {prompt!r}")
    print(f"  reply:  {reply!r}")
    print("  the repository loads and generates correctly")


def main():
    argument_parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    argument_parser.add_argument("--ckpt", required=True)
    argument_parser.add_argument("--out", default="../hf_repo")
    argument_parser.add_argument("--tokenizer-dir", default="../tokenizer")
    argument_parser.add_argument("--repo-id", default=None, help="e.g. yourname/moonfrost-777m-chat")
    argument_parser.add_argument("--dtype", default="bfloat16", choices=["bfloat16", "float16", "float32"])
    argument_parser.add_argument("--tokens", default="an unrecorded number of tokens",
                                  help='e.g. "~4.2 billion tokens"')
    argument_parser.add_argument("--pretrain-data", default="FineWeb-Edu (educational web text)")
    argument_parser.add_argument("--chat-data", default="smol-smoltalk")
    argument_parser.add_argument("--validate", action="store_true", help="load the result back through transformers")
    argument_parser.add_argument("--push", action="store_true", help="upload to --repo-id (run `hf auth login` first)")
    argument_parser.add_argument("--private", action="store_true")
    args = argument_parser.parse_args()

    build_repository(args.ckpt, args.out, args.repo_id, args.dtype, args.tokenizer_dir,
                     args.tokens, args.pretrain_data, args.chat_data)
    if args.validate:
        validate(args.out)

    if args.push:
        if not args.repo_id:
            raise SystemExit("--push needs --repo-id, e.g. --repo-id yourname/moonfrost-777m-chat")
        from huggingface_hub import HfApi, whoami
        try:
            whoami()
        except Exception:
            raise SystemExit("not logged in. Run `hf auth login` yourself first "
                             "(create a WRITE token at https://huggingface.co/settings/tokens)")
        api = HfApi()
        api.create_repo(args.repo_id, private=args.private, exist_ok=True, repo_type="model")
        api.upload_folder(folder_path=args.out, repo_id=args.repo_id, repo_type="model")
        print(f"\nuploaded: https://huggingface.co/{args.repo_id}")


if __name__ == "__main__":
    main()
