"""Writes the loss curves the site draws, straight out of the training logs.

The site keeps every figure in one module so the page cannot contradict itself, and the
loss curves are no exception: rather than hand-copying points, this reads docs/logs/*.jsonl
and emits moonfrost-site/lib/curves.ts. Train curves are thinned, since an SVG does not
need a thousand points to show a shape; validation curves are kept whole, because that is
where the quoted numbers come from.

    python training/export_curves.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
LOGS = os.path.join(HERE, "..", "docs", "logs")
OUT = os.path.join(HERE, "..", "..", "moonfrost-site", "lib", "curves.ts")

# title, note, y clip, then the segments that survive for it: (train log, val log, thinning).
# The clip is (low, high, "what the curve opens at") or None for a panel that needs none.
STAGES = [
    ("Pretraining, phase 1",
     "9,542 steps, 227 min. Steps 1,730-9,160 were never logged: the run that finished "
     "phase 1 lost its log with the machine, and what is drawn either side of the gap is "
     "the attempt that dropped at step 1,730 and the tail read back from retained console "
     "output.",
     (2.85, 5.4, "opens at 10.73"),
     [("base1_train_log.jsonl", "base1_val_log.jsonl", 3),
      ("recovered/phase1_tail_train_log.jsonl", "recovered/phase1_tail_val_log.jsonl", 1)]),
    ("Pretraining, phase 2",
     "340 min in total, of which the first 105 are logged. Loss is nearly flat here "
     "because phase 1 had already taken it to 3.15 and the schedule was annealing.",
     None,
     [("base2_train_log.jsonl", "base2_val_log.jsonl", 6)]),
    ("Chat fine-tune",
     "9,201 steps, 80 min, complete. Validation bottoms out at 1.2484 on step 7,800 and "
     "climbs afterwards, so the released weights are that checkpoint and not the last one.",
     None,
     [("chat_train_log.jsonl", "chat_val_log.jsonl", 16)]),
]


def read(filename):
    path = os.path.join(LOGS, filename)
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as handle:
        rows = [json.loads(line) for line in handle if line.strip()]
    rows.sort(key=lambda row: row.get("step", 0))
    return rows


def thin(rows, every):
    """Every nth point, with the last one always kept so the curve ends where the run did."""
    kept = rows[::every]
    if rows and kept[-1] is not rows[-1]:
        kept.append(rows[-1])
    return kept


def pairs(rows, key):
    return "[" + ", ".join(f"[{row['step']}, {round(row[key], 4)}]" for row in rows) + "]"


def main():
    lines = [
        "/**",
        " * Loss curves for the three training stages, generated by training/export_curves.py",
        " * from the JSONL logs the runs wrote. Do not edit by hand: rerun the script.",
        " *",
        " * Each point is [step, loss]. Train curves are thinned for the SVG; validation",
        " * curves are whole, since the numbers quoted elsewhere on the page are read off them.",
        " */",
        "",
        "export type Curve = Array<[number, number]>;",
        "",
        "export const LOSS_CURVES: Array<{",
        "  title: string;",
        "  note: string;",
        "  clip: { low: number; high: number; opens: string } | null;",
        "  segments: Array<{ train: Curve; val: Curve }>;",
        "}> = [",
    ]

    for title, note, clip, segments in STAGES:
        lines.append("  {")
        lines.append(f"    title: {json.dumps(title)},")
        lines.append(f"    note: {json.dumps(note)},")
        if clip is None:
            lines.append("    clip: null,")
        else:
            low, high, opens = clip
            lines.append(f"    clip: {{ low: {low}, high: {high}, opens: {json.dumps(opens)} }},")
        lines.append("    segments: [")
        for train_file, val_file, every in segments:
            train = thin(read(train_file), every)
            val = read(val_file)
            lines.append("      {")
            lines.append("        train: " + pairs(train, "loss") + ",")
            lines.append("        val: " + pairs(val, "val_loss") + ",")
            lines.append("      },")
        lines.append("    ],")
        lines.append("  },")

    lines.append("];")
    lines.append("")

    path = os.path.abspath(OUT)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as handle:
        handle.write("\n".join(lines))
    print("wrote", path)


if __name__ == "__main__":
    main()
